packages:
  - packages/*
  - apps/*
  - tools/*

catalog:
  "@types/node": ^24
  "@vue/compiler-core": ^3.5.33
  "@vue/compiler-sfc": ^3.5.33
  "@vue/server-renderer": ^3.5.33
  "@vue/shared": ^3.5.33
  vue: ^3.5.33
  bumpp: ^11.0.1
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@0.1.18
  vite-plus: 0.1.18
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.18

catalogMode: prefer

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
